### Teste do endpoint GET /
GET http://localhost:3000/ HTTP/1.1

### Teste do endpoint POST /auth/register
POST http://localhost:3000/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "Ju",
  "email": "ju@email.com",
  "password": "123456",
  "confirmpassword": "123456"
}

### Teste do endpoint POST /auth/login
POST http://localhost:3000/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "isa@email.com",
  "password": "123456"
}


### Teste ID 

GET http://localhost:3000/users/67b7736b9f287d5b1752d0 HTTP/1.1

### Buscar usuário pelo ID
GET http://localhost:3000/users/67b7736b9f287d5b175822d0 HTTP/1.1